const fs = require('node:fs/promises');
const { test, expect, expectScrollSettled } = require('./fixtures');

const sections = ['pupil-trends', 'forecast-checks', 'school-places', 'year-groups', 'budget', 'other-proposals', 'methodology'];
const chartSections = ['pupil-trends', 'school-places', 'year-groups'];
// Independently checked against the DfE May capacity files and January census.
// Keep these dated source checks separate from values generated by the page.
const sourceChecks = [
  { urn: '133343', name: 'Kew Riverside Primary School', rolls: [142, 107, 102, 90], capacity: 210 },
  { urn: '102884', name: 'Darell', rolls: [177, 193, 194, 177], capacity: 420 },
  { urn: '102921', name: "The King's", rolls: [366, 394, 398, 392], capacity: 420 },
];

async function activate(locator, hasTouch) {
  if (hasTouch) await locator.tap();
  else await locator.click();
}

async function openComparison(page, id = 'pupil-trends-detail') {
  const detail = page.locator('#' + id);
  if (!(await detail.evaluate(node => node.open))) await detail.locator(':scope > summary').click();
}

async function expectTrendMode(page, mode) {
  const counts = page.getByRole('button', { name: 'Pupil numbers', exact: true });
  const change = page.getByRole('button', { name: 'Percentage change', exact: true });
  await expect(counts).toHaveAttribute('aria-pressed', String(mode === 'count'));
  await expect(change).toHaveAttribute('aria-pressed', String(mode === 'change'));
  await expect(page.locator(`[data-trend-view="${mode}"]`)).toBeVisible();
  await expect(page.locator(`[data-trend-view="${mode === 'count' ? 'change' : 'count'}"]`)).toBeHidden();
  const charts = page.locator(`[data-trend-view="${mode}"] svg`);
  await expect(charts).toHaveCount(3);
  for (const chart of await charts.all()) {
    await expect(chart).toHaveAttribute('role', 'img');
    await expect(chart).toHaveAccessibleName(/\S/);
  }
  await expect(page.locator('#trend-status')).toContainText(mode === 'count' ? /pupil|number/i : /percentage|%/i);
}

test('Understand: evidence comparison preview leads directly to the visual explanation', async ({ page, hasTouch }) => {
  await page.goto('/evidence.html#evidence');
  const preview = page.getByRole('complementary', { name: 'How does Kew Riverside Primary School compare?' });
  await expect(preview).toBeVisible();
  await expect(preview).toContainText(/pupil trends, school places and year-group sizes/i);
  await activate(preview.getByRole('link', { name: /Understand the situation/ }), hasTouch);
  await expect(page).toHaveURL(/understand.html$/);
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  await expect(page.locator('#pupil-trends-detail')).not.toHaveAttribute('open', '');
});

test('Understand: the existing comparisons and new case questions are readable on arrival', async ({ page }) => {
  await page.goto('/understand.html');
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  for (const id of sections) {
    await expect(page.locator('#' + id)).toBeVisible();
    await expect(page.locator('#' + id).getByRole('heading', { level: 2 })).toBeVisible();
  }
  await expect(page.getByRole('group', { name: 'Pupil trend measure' })).toBeHidden();
  await expect(page.locator('main svg:visible')).toHaveCount(0);
  for (const detail of await page.locator('[data-overview-detail]').all()) {
    await expect(detail).not.toHaveAttribute('open', '');
    await expect(detail.locator(':scope > summary')).toBeVisible();
  }
  await expect(page.locator('#pupil-trends > .data-context')).toContainText('not why');
  await expect(page.locator('#school-places > .data-context')).toContainText('not a current vacancy');
  await expect(page.locator('#year-groups > .data-context')).toContainText('not the September');
  await expect(page.locator('#forecast-checks > .data-context')).toContainText('one forecast vintage and one period');
});

test('Understand: homepage numbers route reaches dated finances and forecast checks', async ({ page, hasTouch }) => {
  await page.goto('/index.html');
  await activate(page.locator('#find-your-way a[href="understand.html"]'), hasTouch);
  await expect(page).toHaveURL(/understand\.html$/);
  const budgetLink = page.locator('.visual-route a[href="#budget"]');
  const forecastLink = page.locator('.visual-route a[href="#forecast-checks"]');
  await expect(budgetLink).toBeVisible();
  await expect(forecastLink).toBeVisible();
  await activate(budgetLink, hasTouch);
  await expect(page.locator('#budget')).toBeInViewport();
  await expect(page.locator('#budget')).toContainText('31 March 2026');
  await expect(page.locator('#budget')).toContainText('£231,685');
  await expect(page.locator('#budget')).toContainText(/forecast|project/i);
  await expect(page.locator('#budget a[href="evidence.html#source-school-balances-mar-2026"]')).toBeVisible();
  await expect(page.locator('#budget a[href="evidence.html#source-consultation-kew-faq"]')).toBeVisible();
  await activate(forecastLink, hasTouch);
  await expect(page.locator('#forecast-checks')).toBeInViewport();
  await expect(page.locator('#forecast-checks')).toContainText(/Kew planning area/i);
  await expect(page.locator('#forecast-checks')).toContainText('2025/26');
  await expect(page.locator('#forecast-checks a[href="evidence.html#source-kew-area-forecast-2025"]')).toBeVisible();
});

test('Understand: financial actuals, council projection and forecast error keep distinct meanings', async ({ page }) => {
  await page.goto('/understand.html#budget');
  const budget = page.locator('#budget');
  await expect(budget).toContainText('£231,685');
  await expect(budget).toContainText(/£400,000/);
  await expect(budget).toContainText('indicative forecasts, not the approved budget or cash available today');
  await expect(page.locator('#closure-costs')).toBeVisible();
  await expect(page.locator('#closure-costs')).toContainText('£69,640');
  await expect(page.locator('#closure-costs')).toContainText(/not (the|a) (saving|council)|does not (establish|show|equal)/i);
  const forecast = page.locator('#forecast-checks');
  await expect(forecast).toContainText('651');
  await expect(forecast).toContainText('654');
  await expect(forecast).toContainText('88');
  await expect(forecast).toContainText('97');
  await expect(forecast).toContainText(/one (period|vintage)|single (period|vintage)/i);
  await expect(forecast).toContainText(/revision/i);
});

test('Understand: optional financial table opens by keyboard and has a stable direct link', async ({ page }) => {
  await page.goto('/understand.html');
  // Keep this check on the historical five-year table when other details precede it.
  const details = page.locator('#budget-actuals');
  const summary = details.locator('summary');
  await expect(summary).toBeVisible();
  await summary.focus();
  await page.keyboard.press('Enter');
  await expect(details).toHaveAttribute('open', '');
  const table = details.locator('table').last();
  await expect(table).toBeVisible();
  await expect(table.locator('tbody tr')).toHaveCount(5);
  await expect(table.locator('caption')).toHaveText(/financial|income|reserve|actual/i);
  await page.goto('/understand.html#closure-costs');
  await expect(page.locator('#closure-costs')).toBeInViewport();
});

test('Understand: count and percentage controls change the charts and accessible state', async ({ page, hasTouch }) => {
  await page.goto('/understand.html');
  await openComparison(page);
  await expectTrendMode(page, 'count');
  await activate(page.getByRole('button', { name: 'Percentage change', exact: true }), hasTouch);
  await expectTrendMode(page, 'change');
  await activate(page.getByRole('button', { name: 'Pupil numbers', exact: true }), hasTouch);
  await expectTrendMode(page, 'count');
});

test('Understand: measure buttons work with a keyboard and retain visible focus', async ({ page, browserName }) => {
  const next = browserName === 'webkit' && process.platform === 'darwin' ? 'Alt+Tab' : 'Tab';
  await page.goto('/understand.html');
  await openComparison(page);
  const counts = page.getByRole('button', { name: 'Pupil numbers', exact: true });
  const change = page.getByRole('button', { name: 'Percentage change', exact: true });
  await counts.focus();
  await page.keyboard.press(next);
  await expect(change).toBeFocused();
  await page.keyboard.press('Enter');
  await expectTrendMode(page, 'change');
  await expect(change).toBeFocused();
  await page.keyboard.press('Shift+' + next);
  await expect(counts).toBeFocused();
  await page.keyboard.press('Space');
  await expectTrendMode(page, 'count');
});

test('Understand: each borough comparison opens and closes independently', async ({ page, hasTouch }) => {
  await page.goto('/understand.html');
  for (const id of chartSections) {
    await test.step(id, async () => {
      await openComparison(page, id + '-detail');
      const section = page.locator('#' + id);
      const summary = section.locator('summary').filter({ hasText: /^Compare all Richmond primary schools$/ });
      await expect(summary).toHaveCount(1);
      const details = summary.locator('..');
      await expect(details).not.toHaveAttribute('open', '');
      await activate(summary, hasTouch);
      await expect(details).toHaveAttribute('open', '');
      await expect(details.locator('table')).toBeVisible();
      await expect(details.locator('tbody tr')).toHaveCount(45);
      await activate(summary, hasTouch);
      await expect(details).not.toHaveAttribute('open', '');
    });
  }
});

test('Understand: underlying local and borough tables remain available in either chart mode', async ({ page, hasTouch }) => {
  await page.goto('/understand.html');
  await openComparison(page);
  const trend = page.locator('#pupil-trends');
  const localSummary = trend.locator('summary').filter({ hasText: /^View the local trend data$/ });
  const boroughSummary = trend.locator('summary').filter({ hasText: /^Compare all Richmond primary schools$/ });
  await activate(localSummary, hasTouch);
  await activate(boroughSummary, hasTouch);
  const localTable = localSummary.locator('..').locator('table');
  const boroughTable = boroughSummary.locator('..').locator('table');
  await expect(localTable).toBeVisible();
  await expect(boroughTable).toBeVisible();
  const localBefore = await localTable.textContent();
  const boroughBefore = await boroughTable.textContent();
  await activate(page.getByRole('button', { name: 'Percentage change', exact: true }), hasTouch);
  await expectTrendMode(page, 'change');
  await expect(localTable).toHaveText(localBefore);
  await expect(boroughTable).toHaveText(boroughBefore);
});

test('Understand: disclosures work through native keyboard interaction', async ({ page }) => {
  await page.goto('/understand.html');
  await openComparison(page);
  const summary = page.locator('#pupil-trends summary').filter({ hasText: /^View the local trend data$/ });
  await summary.focus();
  await page.keyboard.press('Enter');
  await expect(summary.locator('..').locator('table')).toBeVisible();
  await expect(summary).toBeFocused();
  await page.keyboard.press('Space');
  await expect(summary.locator('..')).not.toHaveAttribute('open', '');
});

test('Understand: charts and expanded tables fit a narrow viewport in both modes', async ({ page, hasTouch }) => {
  await page.setViewportSize({ width: 320, height: 844 });
  await page.goto('/understand.html');
  await openComparison(page);
  for (const name of ['Percentage change', 'Pupil numbers']) {
    await activate(page.getByRole('button', { name, exact: true }), hasTouch);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    for (const chart of await page.locator('main svg:visible').all()) {
      const box = await chart.boundingBox();
      expect(box.width).toBeGreaterThan(0);
      expect(box.x).toBeGreaterThanOrEqual(0);
      expect(box.x + box.width).toBeLessThanOrEqual(321);
    }
  }
  for (const id of chartSections) {
    await openComparison(page, id + '-detail');
    await activate(page.locator('#' + id + ' summary').filter({ hasText: /^Compare all Richmond primary schools$/ }), hasTouch);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  }
});

test('Understand: school dataset downloads as CSV', async ({ page }) => {
  await page.goto('/understand.html');
  const link = page.locator('a[download][href="richmond-schools.csv"]').first();
  await expect(link).toHaveAccessibleName(/\S/);
  const [download] = await Promise.all([page.waitForEvent('download'), link.click()]);
  expect(download.suggestedFilename()).toMatch(/\.csv$/);
  expect(await download.failure()).toBeNull();
  const contents = await fs.readFile(await download.path(), 'utf8');
  expect(contents).toContain('Kew Riverside Primary School');
  expect(contents).toContain('Darell');
  expect(contents).toMatch(/The King['’]s/);
});

test('Understand: visible trend points, percentage baseline and local table match audited counts', async ({ page, hasTouch }) => {
  await page.goto('/understand.html');
  await openComparison(page);
  const normaliseNumber = value => Number(value.replaceAll('−', '-').replace(/[+%,\s]/g, ''));
  for (const expected of sourceChecks) {
    const chart = page.locator(`[data-trend-view="count"] figure[data-school="${expected.urn}"]`);
    expect((await chart.locator('.end-value').allTextContents()).map(normaliseNumber)).toEqual(expected.rolls);
  }
  await activate(page.getByRole('button', { name: 'Percentage change', exact: true }), hasTouch);
  for (const expected of sourceChecks) {
    const changes = expected.rolls.map(roll => Number(((roll / expected.rolls[0] - 1) * 100).toFixed(1)));
    const chart = page.locator(`[data-trend-view="change"] figure[data-school="${expected.urn}"]`);
    expect((await chart.locator('.end-value').allTextContents()).map(normaliseNumber)).toEqual(changes);
    expect(Number(await chart.locator('circle').first().getAttribute('cy'))).toBe(Number(await chart.locator('.baseline').getAttribute('y1')));
  }
  const summary = page.locator('#pupil-trends summary').filter({ hasText: /^View the local trend data$/ });
  await activate(summary, hasTouch);
  const table = summary.locator('..').locator('table');
  await expect(table.locator('tbody tr')).toHaveCount(3);
  for (const expected of sourceChecks) {
    const cells = await table.locator(`tr[data-school="${expected.urn}"] td`).allTextContents();
    expect(cells.slice(0, 4).map(normaliseNumber)).toEqual(expected.rolls);
    expect(normaliseNumber(cells.at(-1))).toBe(Number(((expected.rolls.at(-1) / expected.rolls[0] - 1) * 100).toFixed(1)));
  }
});

test('Understand: capacity and cohort graphics keep their dates, units and source values distinct', async ({ page }) => {
  await page.goto('/understand.html');
  await openComparison(page, 'school-places-detail');
  await openComparison(page, 'year-groups-detail');
  await expect(page.locator('#school-places .data-date')).toContainText('May 2025');
  await expect(page.locator('#year-groups .data-date')).toContainText('January 2026');
  for (const expected of sourceChecks) {
    const row = page.locator(`.place-row[data-school="${expected.urn}"]`);
    const roll = expected.rolls.at(-1);
    const unfilled = expected.capacity - roll;
    const occupied = (roll / expected.capacity * 100).toFixed(1);
    await expect(row.locator('.place-total')).toHaveText(`${roll} pupils / ${expected.capacity} reported places`);
    await expect(row.locator('svg')).toHaveAccessibleName(new RegExp(`${occupied.replace('.', '\\.')}% occupied; ${unfilled} unfilled places`));
    expect(Number(await row.locator('.place-filled').getAttribute('width'))).toBeCloseTo(roll / expected.capacity * 100, 3);
  }
  const kew = page.locator('.cohort-row[data-school="133343"]');
  await expect(kew.locator('p')).toContainText('84 pupils');
  await expect(kew.locator('.cohort-cell strong')).toHaveText([
    'Reception: 14', 'Year 1: 8', 'Year 2: 10', 'Year 3: 11', 'Year 4: 18', 'Year 5: 14', 'Year 6: 9',
  ]);
  await expect(page.locator('#year-groups .chart-footnote')).toContainText('not the September 2026 roll');
  await expect(page.locator('#school-places .chart-footnote')).toContainText('not a current vacancy list');
});

test('Understand: questions, source references and proposal comparison lead to the cited context', async ({ page, hasTouch }) => {
  for (const id of chartSections) {
    await page.goto('/understand.html');
    await activate(page.locator(`.visual-route a[href="#${id}"]`), hasTouch);
    await expect(page).toHaveURL(new RegExp(`#${id}$`));
    await expect(page.locator('#' + id)).toBeInViewport();
  }
  for (const [section, source] of [
    ['pupil-trends', 'school-capacity-may-2025'],
    ['year-groups', 'school-census-jan-2026'],
    ['other-proposals', 'hampton-wick-proposal-2026'],
  ]) {
    await page.goto('/understand.html');
    await activate(page.locator(`#${section} a[href="evidence.html#source-${source}"]`).first(), hasTouch);
    await expect(page).toHaveURL(new RegExp(`evidence.html#source-${source}$`));
    await expect(page.locator('#source-' + source)).toBeInViewport();
  }
  await page.goto('/understand.html');
  const comparison = page.locator('#other-proposals');
  await expect(comparison.locator('.proposal-comparison article')).toHaveCount(2);
  await expect(comparison.locator('.section-lead')).toContainText('neither is a final decision');
  await openComparison(page, 'other-proposals-detail');
  await activate(comparison.getByRole('link', { name: /Read the Kew proposal/ }), hasTouch);
  await expect(page).toHaveURL(/proposal.html$/);
});

test('Understand: published data keeps dated measurements and school-level totals consistent', async ({ page }) => {
  const response = await page.request.get('/understand-data.json');
  expect(response.ok()).toBe(true);
  const data = await response.json();
  expect(data.schemaVersion).toBe(1);
  expect(data.nearbyUrns).toEqual(sourceChecks.map(item => item.urn));
  expect(data.years.map(year => year.key)).toEqual(['202122', '202223', '202324', '202425']);
  expect(data.years.map(year => year.censusMonth)).toEqual(['2022-05', '2023-05', '2024-05', '2025-05']);
  expect(data.schools).toHaveLength(45);
  expect(new Set(data.schools.map(school => school.urn)).size).toBe(45);
  for (const expected of sourceChecks) {
    const school = data.schools.find(item => item.urn === expected.urn);
    expect(school.name).toContain(expected.name);
    expect(school.history.map(year => year.roll)).toEqual(expected.rolls);
    expect(school.capacity2025.capacity).toBe(expected.capacity);
    expect(school.capacity2025.roll).toBe(expected.rolls.at(-1));
  }
  const kew = data.schools.find(school => school.urn === '133343');
  expect(kew.cohorts2026.counts).toEqual([14, 8, 10, 11, 18, 14, 9]);
  expect(kew.cohorts2026.totalExcludingNursery).toBe(84);
  expect(kew.capacity2025.roll).toBe(90);
  expect(data.sources.find(source => source.id === 'dfe-capacity-2025').measurementDate).toBe('2025-05');
  expect(data.sources.find(source => source.id === 'dfe-census-2026').measurementDate).toBe('2026-01');
  for (const school of data.schools) {
    const capacity = school.capacity2025;
    expect(capacity.occupancyPercent).toBeCloseTo(capacity.roll / capacity.capacity * 100, 3);
    expect(capacity.unfilledPlaces).toBe(Math.max(0, capacity.capacity - capacity.roll));
    expect(capacity.pupilsOverCapacity).toBe(Math.max(0, capacity.roll - capacity.capacity));
    expect(school.cohorts2026.counts.reduce((sum, value) => sum + value, 0)).toBe(school.cohorts2026.totalExcludingNursery);
  }
  for (const total of data.borough) {
    const histories = data.schools.map(school => school.history.find(year => year.year === total.year));
    expect(histories).toHaveLength(total.schoolCount);
    expect(histories.reduce((sum, year) => sum + year.roll, 0)).toBe(total.roll);
    expect(histories.reduce((sum, year) => sum + year.capacity, 0)).toBe(total.capacity);
  }
});

test('Understand: a failed enhancement script preserves readable charts and native data disclosures', async ({ page, hasTouch }) => {
  await page.route('**/understand.js*', route => route.fulfill({ status: 404, body: 'Intentional test outage', headers: { 'X-Test-Fixture': 'intentional-error' } }));
  await page.goto('/understand.html');
  const controls = page.locator('[role="group"][aria-label="Pupil trend measure"]');
  await expect(controls).toHaveCount(1);
  await expect(controls).toBeHidden();
  await expect(page.locator('[data-trend-view="count"]')).toBeVisible();
  await expect(page.locator('[data-trend-view="count"] svg')).toHaveCount(3);
  const summary = page.locator('#pupil-trends summary').filter({ hasText: /^View the local trend data$/ });
  await activate(summary, hasTouch);
  await expect(summary.locator('..').locator('table')).toBeVisible();
  await expect(page.locator('#other-proposals')).toBeVisible();
  await expect(page.locator('#methodology')).toBeVisible();
});


test('Understand: optional detail reveals by keyboard and incoming links recover through history', async ({ page, hasTouch }) => {
  await page.goto('/understand.html#pupil-trends');
  const detail = page.locator('#pupil-trends-detail');
  const summary = detail.locator(':scope > summary');
  await summary.focus();
  await page.keyboard.press('Enter');
  await expectTrendMode(page, 'count');
  await expect(summary).toBeFocused();
  await page.keyboard.press('Space');
  await expect(detail).not.toHaveAttribute('open', '');

  for (const target of ['forecast-method', 'closure-costs', 'attainment-chart', 'inspection-summary', 'mixed-age-curriculum']) {
    await page.goto('/understand.html#pupil-trends');
    await page.evaluate(id => { location.hash = id; }, target);
    await expectScrollSettled(page, 'Detail fragment arrival');
    await expect(page.locator('#' + target)).toBeVisible();
    await expect(page.locator('#' + target)).toBeInViewport();
    await page.goBack();
    await expect(page).toHaveURL(/#pupil-trends$/);
    await page.goForward();
    await expect(page.locator('#' + target)).toBeInViewport();
  }

  await page.goto('/understand.html#forecast-method');
  await expect(page.locator('#forecast-detail')).toHaveAttribute('open', '');
  await expect(page.locator('#forecast-method')).toHaveAttribute('open', '');
  await page.goto('/understand.html#attainment-chart');
  await expect(page.locator('#attainment-detail')).toHaveAttribute('open', '');
  await expect(page.locator('#attainment-chart')).toBeInViewport();
});

test('Understand: the short-answer view reflows with text enlarged to 200 percent', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 });
  await page.goto('/understand.html');
  const heading = page.getByRole('heading', { level: 1 });
  const originalSize = await heading.evaluate(node => parseFloat(getComputedStyle(node).fontSize));
  // Capture first, then apply: nested text must not be multiplied more than once.
  // This is controlled text enlargement, not native Safari text zoom.
  await page.evaluate(() => {
    const elements = [...document.querySelectorAll('h1,h2,h3,p,a,label,summary,button,li,span,strong,small,dt,dd')];
    const sizes = elements.map(element => parseFloat(getComputedStyle(element).fontSize) * 2);
    elements.forEach((element, index) => { element.style.fontSize = sizes[index] + 'px'; });
  });
  await expect(heading).toHaveCSS('font-size', `${originalSize * 2}px`);
  const overflow = await page.locator('main').evaluate(main => {
    const width = innerWidth;
    return [...main.querySelectorAll('.understand-hero, .understand-hero > *, .understand-hero h1, .data-section, .data-method')]
      .filter(element => { const box = element.getBoundingClientRect(); return box.left < -1 || box.right > width + 1 || element.scrollWidth > element.clientWidth + 1; })
      .map(element => element.id || element.className || element.tagName);
  });
  expect(overflow).toEqual([]);
  await expect(page.locator('.visual-route a')).toHaveCount(8);
  await expect(page.locator('#pupil-trends-detail > summary')).toBeVisible();
});

test('Understand: arrival explains three dated findings before asking readers to choose a topic', async ({ page, hasTouch }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/understand.html');
  const findings = page.locator('.number-findings');
  const items = findings.locator(':scope > article');
  await expect(items).toHaveCount(3);
  for (const item of await items.all()) await expect(item).toBeVisible();
  const [pupils, finances, forecasts] = await items.all();
  for (const value of ['36.6%', '5.5%', '45 primary-phase schools', 'May 2022', 'May 2025', 'excluding nursery', 'not its cause']) {
    await expect(pupils).toContainText(value);
  }
  for (const value of ['£231,685.09', '31 March 2026', 'more than £400,000', 'accumulated deficit', '2028/29', 'approved budget, ledger and assumptions remain missing', 'long-term viability']) {
    await expect(finances).toContainText(value);
  }
  for (const value of ['2025/26', 'January 2026', '651', '654', '88 forecast, 97 counted', 'one period across three schools', 'excluding nursery', 'not a forecast for Kew Riverside Primary School alone or a long-term accuracy test']) {
    await expect(forecasts).toContainText(value);
  }
  const insightBox = await findings.boundingBox();
  const topicsBox = await page.locator('.visual-route').boundingBox();
  expect(insightBox.y + insightBox.height).toBeLessThan(topicsBox.y);
  // Every short finding has a working route to its full sourced explanation.
  for (const target of ['pupil-trends', 'budget', 'forecast-checks']) {
    await activate(findings.locator(`a[href="#${target}"]`), hasTouch);
    await expect(page.locator('#' + target)).toBeInViewport();
    await expect(page).toHaveURL(new RegExp(`#${target}$`));
  }
});
