"""Build the optional historical-research pages from reviewed public data. Standard library only."""
from pathlib import Path
from build_navigation import render_navigation
import json,html,re,argparse
ROOT=Path(__file__).resolve().parents[2]
D=json.loads((ROOT/'lessons-data.json').read_text())
C=D['catalogue'];F=D['comparisons'];E=D['exhibits'];S=D['sources'];Q=D['claims']
esc=lambda s:html.escape(str(s),quote=True)
def refs(ids):return ' · '.join(f'<a href="lessons-sources.html#{esc(i)}">{esc(i)}</a>' for i in ids)
def table(headers,rows,caption):
 return '<div class="lesson-table-wrap" role="region" aria-label="'+esc(caption)+'" tabindex="0"><table><caption>'+esc(caption)+'</caption><thead><tr>'+''.join('<th scope="col">'+esc(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">' if i==0 else '<td>')+esc(v)+('</th>' if i==0 else '</td>') for i,v in enumerate(r))+'</tr>' for r in rows)+'</tbody></table></div>'
def money(n):return ('−' if n<0 else '')+'£'+f'{abs(n):,}'
# Same shared navigation, security policy and local assets as the proposal page.
base=(ROOT/'proposal.html').read_text()
header=re.sub(r'<link rel="stylesheet" href="lessons\.css\?v=\d+">','',base[:base.index('<main')].replace(' aria-current="page"',''))
footer=base[base.index('<footer'):]
def page(title,body):
 h=re.sub(r'(?:Timetable checked|Proposal checked|Evidence updates:) [^<]+', 'Research checked 22 September 2026', header)
 h=re.sub(r'<title>.*?</title>','<title>'+esc(title)+' | Kew Riverside Primary School</title>',h)
 h=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="Selected school closure reprieves and comparisons, with eight graphics, a full case catalogue and complete citations. Evidence and limits for Kew Riverside Primary School families.">',h)
 h=h.replace('</head>','<link rel="stylesheet" href="lessons.css?v=2026092401"><script src="lessons.js" defer></script></head>')
 return h+'<main id="main" class="lessons-page wrap">'+body+'</main>'+footer
method=[]
for block in D['methodology'].strip().split('\n\n'):
 if block.startswith('# '):continue
 if block.startswith('## '):method.append('<h3>'+esc(block[3:])+'</h3>')
 elif block.startswith('- '):method.append('<ul>'+''.join('<li>'+esc(t[2:])+'</li>' for t in block.splitlines() if t.startswith('- '))+'</ul>')
 else:method.append('<p>'+esc(block).replace('\n',' ')+'</p>')
text_data={
1:table(['Stage where proposal stopped','Schools','Names'],[['Initial consultation',3,'Fletching; Godshill; St George’s, Langton'],['Local decision after notice',3,'Brading; Oakfield; Wroxall'],['External intervention',6,'Arreton; St John the Divine; Fenstanton; Holy Trinity; Pooles Park; Hazlewood']],'12 selected schools; not national success rates'),
2:table(['Decision episode','Schools']+[x['label'] for x in C['reason_columns']],[[r['label'],r['n_schools']]+[{0:'Not established',1:'Discussed / route',2:'Explicit rationale'}[v] for v in r['values']] for r in C['reason_episodes']],'Nine grouped episodes: overlapping reasons, coded by one analyst')+'<p>A blank or “not established” is not evidence that a factor was absent or ineffective. No independent second coding was performed.</p>'+''.join('<p><strong>'+esc(r['label'])+':</strong> '+esc(r['note'])+' '+refs(r['sources'])+'</p>' for r in C['reason_episodes']),
3:table(['School(s)','Decision / outcome date','Outcome'],[['Godshill','12 December 2024','Removed before notice'],['Brading; Oakfield; Wroxall','20 March 2025','Cabinet did not proceed'],['Arreton','23 June 2025','Closure rejected by adjudicator'],['Cowes','31 August 2025','School closed']],'All six original Isle of Wight proposals; one local programme'),
4:table(['Year','Original forecast','Revised: optimistic pupils','Revised: cautious pupils'],[[y,money(C['fletching_budget']['original'][i]),money(C['fletching_budget']['revised_optimistic'][i]),money(C['fletching_budget']['revised_cautious'][i])] for i,y in enumerate(C['fletching_budget']['years'])],'Fletching forecast year-end balances; not annual losses or actual results')+'<p><strong>Support:</strong> £44,368 fundraising raised; £20,000 trust pledge; £10,000 parish resolution. The £74,368 combined total is not all cash received. The forecast also reflects other assumptions; the third-year range is a pupil scenario, not a confidence interval.</p>',
5:'<ol><li><strong>30 June 2026:</strong> the Hazlewood merger proposal was rejected.</li><li><strong>Same determination:</strong> capital for replacement buildings remained an unresolved problem; the adjudicator contemplated future closure.</li><li><strong>15 September 2026:</strong> a renewed closure proposal was reported. The register listed the school open on 22 September.</li></ol><p>Track a stopped proposal separately from a viable long-term future. This research does not predict how Hazlewood’s case will end.</p>',
6:'<dl>'+''.join('<dt>'+esc(p['timing']+' · '+p['work'])+'</dt><dd>'+esc(p['deliverable'])+'</dd>' for p in C['priorities'])+'</dl><p>Suggested priorities are editorial judgement, not measured effectiveness. Kew is a community school; historic faith-school referral routes and rural protections must not be assumed to apply.</p>',
7:'<ul>'+''.join('<li><strong>'+esc(s['name'])+':</strong> '+esc(s['outcome'])+' '+esc(s['partial_benefit'])+' <a href="#case-'+esc(s['id'])+'">Read the case and its limits</a></li>' for s in F['schools'])+'</ul>',
8:table(['School','Online signatures','Paper signatures (separate)','Outcome by 31 August 2025'],[[r['label'],f'{r["online"]:,}',f'{r["paper"]:,}' if r['paper'] is not None else 'Not stated',r['outcome']] for r in F['petition_snapshot']['schools']],'Autumn 2024 petition snapshot, reported March 2025')+'<p>Online total: 3,771. Paper signatures are not added because overlap is unknown. Counts are not adjusted for school size, campaign duration or signatory residence. This does not establish a causal effect or a signature threshold.</p>'}
ex_refs={1:['S01','S03','S05','S07','S08','S10','S11','S13','S15'],2:['S01','S03','S05','S07','S08','S10','S11','S13','S15'],3:['S03','S05','S07','S28','G12'],4:['S01','S02'],5:['S15','S16','G11'],6:['S01','S07','S08','S11','S17','S18','S22'],7:['S23','S24','S25','S27','G12','G13','G14','G15'],8:['S27','S03','S05','S07','S28','G12']}
short={1:'Where did proposals stop?',2:'What reasons appear in decisions?',3:'What happened to one whole local group?',4:'Can funding buy time without fixing a deficit?',5:'Does a reprieve mean recovery?',6:'What could we work on now?',7:'Why did some alternatives fall short?',8:'What can petition counts tell us?'}
figures=[]
for num in [2,4,6,7,1,3,5,8]:
 e=E[num-1];asset='lessons-'+e['file']
 figures.append(f'''<details class="lesson-exhibit" id="exhibit-{num}"><summary><span class="lesson-number">{num:02}</span><span><strong>{esc(short[num])}</strong><span class="lesson-subtitle">{esc(e['title'])}</span></span></summary><div class="lesson-exhibit-body"><figure><img src="{asset}.svg" alt="{esc(e['description'])}" width="1600" height="1000" loading="lazy"><figcaption>{esc(e['description'])}</figcaption></figure><div class="lesson-downloads"><a href="{asset}.svg">Open full-size graphic</a><a href="{asset}.png" download>Download PNG (4800 × 3000)</a></div><p class="source-note">Sources: {refs(ex_refs[num])}. <a href="lessons-sources.html#X{num:02}">Evidence and interpretation</a>.</p><details class="lesson-data"><summary>Read the chart’s data and notes</summary>{text_data[num]}</details></div></details>''')
cases=[]
for c in C['schools']:
 cases.append(f'''<details class="lesson-case" id="case-{esc(c['id'])}" data-outcome="reprieve"><summary><span><strong>{esc(c['short_name'])}</strong><span class="lesson-subtitle">{esc(c['authority'])} · {esc(c['date'])}</span></span><span class="lesson-outcome">{esc(c['outcome'])}</span></summary><div class="lesson-case-body"><h3>{esc(c['name'])}</h3><p class="source-note">{'Primary decision / recommendation record' if c['primary_decision'] else 'Attributed reporting; no independently examined decision rationale'} · {esc(c['type_at_decision'])} · {esc(c['stage'])}</p><dl><dt>What the record supports</dt><dd>{esc(c['reason'])}</dd><dt>Application to Kew · editorial interpretation</dt><dd>{esc(c['lesson'])} {esc(c['transfer'])}</dd><dt>Limits and follow-up</dt><dd>{esc(c['limit'])} {esc(c['current_status'])}.</dd></dl><p class="source-note">{refs(c['sources']+[c['registry_source']])}<br>{esc(c['locator'])}</p></div></details>''')
for c in F['schools']:
 cases.append(f'''<details class="lesson-case closure-case" id="case-{esc(c['id'])}" data-outcome="closure"><summary><span><strong>{esc(c['name'])}</strong><span class="lesson-subtitle">{esc(c['authority'])} · Closed {esc(c['closure_date'])}</span></span><span class="lesson-outcome">Closure comparison</span></summary><div class="lesson-case-body"><p><strong>{esc(c['outcome'])}</strong></p><h3>What was tried</h3><ul>{''.join('<li>'+esc(e['text'])+' '+refs(e['sources'])+'</li>' for e in c['efforts'])}</ul><dl>{''.join('<dt>'+title+'</dt><dd>'+esc(c[key])+'</dd>' for title,key in [('Assessment in the record','reason'),('What changed','partial_benefit'),('Application to Kew · editorial interpretation','lesson'),('Comparison and limits','comparison'),('Evidence limitations','limit')])}</dl><p class="source-note">{refs(c['sources'])}<br>{esc(c['locator'])}</p></div></details>''')
case_names={c['id']:c.get('short_name',c['name']) for c in C['schools']+F['schools']}
def case_links(ids):
 links=[f'<a href="#case-{esc(i)}">{esc(case_names[i])}</a>' for i in ids]
 return links[0] if len(links)==1 else ', '.join(links[:-1])+' and '+links[-1]
lessons=[]
for i,p in enumerate(F['comparison_lessons']):
 outcomes=' '.join('<span>'+case_links(o['case_ids'])+': '+esc(o['text'])+'</span>' for o in p['outcomes'])
 lessons.append(f'''<article id="lesson-{esc(p['id'])}"><h2>{esc(p['theme'])}</h2><p class="lesson-paired-outcomes"><strong>Outcome</strong> {outcomes}</p><p><strong>What the record supports</strong> {esc(p['record'])}</p><p class="lesson-caveat">{esc(p['limit'])}</p><p class="lesson-implication"><strong>Question for Kew <span>· editorial interpretation</span></strong> {esc(p['question'])}</p><p class="source-note">Decision records and follow-up: {refs(p['sources'])}</p></article>''')
body=f'''<p class="lesson-breadcrumb"><a href="proposal.html#other-schools">Proposal &amp; dates</a> / Research to explore</p><header class="lesson-hero lesson-landing-hero"><p class="eyebrow">Historical evidence · Compiled 22 September 2026</p><h1>What can other <br>schools teach us?</h1><p class="lesson-lead"><strong>Selected cases, not odds of success.</strong> Compare 12 reprieve schools across nine decision episodes with four schools that closed.</p></header>
<section class="lesson-section" id="key-lessons" aria-label="Three lessons from the case records"><div class="lesson-takeaways">{''.join(lessons)}</div><div class="lesson-research-routes"><a href="#catalogue">Browse all 16 schools</a><a href="lessons-report.pdf" download>Download full report (PDF)</a></div><aside class="lesson-next"><h3>A question you can use now</h3><p>What evidence, budget assumptions and partner commitments would the council need to assess a viable alternative to closure?</p><a href="feedback.html?kind=meeting#feedback-form">Share a question or supporting evidence →</a><p class="source-note">This is a suggested question, not an official requirement. Sharing here sends it to Yann for review; it does not reach the council. <a href="proposal.html#take-part">Give your views through the official consultation</a> while alternatives are still being assessed.</p></aside></section>
<nav class="proposal-nav" aria-label="Research sections"><a href="#key-lessons">Key lessons</a><a href="#visual-guide">Visual guide</a><a href="#catalogue">All 16 schools</a><a href="#method">Method &amp; limits</a><a href="lessons-sources.html">Full citations</a></nav><p class="source-note">8 optional graphics · 16 named schools · <a href="lessons-sources.html">45 sources and 49 evidence / interpretation entries</a></p>
<section class="lesson-section" id="visual-guide"><p class="eyebrow">Eight ways to understand the evidence</p><h2>Choose a question to explore.</h2><p>Start with the decision reasons, funding, practical work and closure comparisons. Each graphic includes readable data, evidence notes and a full-size download.</p>{''.join(figures)}</section>
<section class="lesson-section" id="catalogue"><p class="eyebrow">The complete catalogue</p><h2>Read the case behind the lesson.</h2><p>All 12 reprieve schools or successors were listed open in GIAS on 22 September 2026. Being “open” does not mean a school has recovered. Hazlewood faces a renewed proposal. Pooles Park continues through an academy successor. The four closure comparisons are selected for context, not a matched control group. Cowes is in both the local group and the comparisons, but it is one school.</p><fieldset class="lesson-filters" id="lesson-filters" hidden><legend>Find a school or theme</legend><label for="lesson-search">Search all cases<input id="lesson-search" type="search" placeholder="Try funding, Lambeth or transition"></label><label for="lesson-outcome">Outcome<select id="lesson-outcome"><option value="all">All outcomes</option><option value="reprieve">Proposal stopped / provision continued</option><option value="closure">School closed</option></select></label><button type="button" id="lesson-reset">Clear filters</button></fieldset><p id="lesson-count" role="status" aria-live="polite">16 schools shown · 12 reprieves and 4 closure comparisons</p><div class="lesson-cases">{''.join(cases)}</div><p id="lesson-empty" hidden>No cases match. Try a broader search or clear the filters.</p></section>
<section class="lesson-section" id="method"><p class="eyebrow">How to read this research</p><h2>Keep the limits beside the lessons.</h2><p>School types, places, dates and access to legal routes differ. The 12 reprieves come from nine grouped decision episodes, and some local decisions are still linked. Neither the cases nor the graphic order measure effectiveness.</p><details class="lesson-method"><summary>Read the complete method and evidence limitations</summary>{''.join(method)}</details><p><a href="lessons-sources.html">Open the complete citations appendix →</a></p></section>'''
source_cards=[]
for s in S:
 used=' · '.join(f'<a href="#{esc(q)}">{esc(q)}</a>' for q in s['used_by'])
 source_cards.append(f'''<article class="lesson-source" id="{esc(s['id'])}"><h3>{esc(s['id'])} · {esc(s['title'])}</h3><p>{esc(s['publisher'])} · {esc(s['type'])}</p><p class="source-note">Published / record date: {esc(s['date'])} · Accessed: {esc(s['accessed'])}</p><a class="lesson-full-url" href="{esc(s['url'])}">{esc(s['url'])}</a><dl><dt>Exact location</dt><dd>{esc(s['locator'])}</dd><dt>Inspection and access</dt><dd>{esc(s['access_method'])} {esc(s.get('integration_check',''))}</dd><dt>Used in</dt><dd>{used}</dd></dl></article>''')
claims=[]
for q in Q:
 claims.append(f'''<details class="lesson-claim" id="{esc(q['id'])}"><summary><span><strong>{esc(q['id'])} · {esc(q['title'])}</strong><span class="lesson-subtitle">{esc(q['kind'])}</span></span></summary><div><p>{esc(q['claim'])}</p><p>{refs(q['sources'])}</p><p class="source-note">{esc(q['locator'])}</p></div></details>''')
appendix=f'''<p class="lesson-breadcrumb"><a href="lessons.html">Lessons from other schools</a> / Citations</p><header class="lesson-hero"><p class="eyebrow">Complete citations appendix · 22 September 2026</p><h1>Follow every claim <br>back to its source.</h1><p class="lesson-lead">45 source records and 49 evidence or interpretation entries. This is the complete register for this research pack, not a bibliography of all school closures.</p><p>Each source keeps its dates, exact location and any limits on how it was inspected. Recommendations are labelled as editorial inferences. Some original records may restrict automated access.</p><div class="button-row"><a class="button primary" href="lessons.html">Back to the research</a><a class="button" href="lessons-report.pdf" download>Download report &amp; appendix (PDF)</a></div></header><nav class="proposal-nav" aria-label="Appendix sections"><a href="#source-register">45 source records</a><a href="#claim-ledger">49 claims &amp; interpretations</a><a href="lessons.html#method">Method &amp; limits</a></nav><section class="lesson-section" id="source-register"><h2>The source register</h2><nav class="lesson-source-index" aria-label="Source identifiers">{''.join('<a href="#'+esc(s['id'])+'">'+esc(s['id'])+'</a>' for s in S)}</nav>{''.join(source_cards)}</section><section class="lesson-section" id="claim-ledger"><h2>Evidence and interpretation ledger</h2><p>Open an entry to see its claim, sources and exact location. IDs such as S01 and G01 are sources. The other IDs describe cases, exhibits and interpretations.</p>{''.join(claims)}</section>'''
outputs={'lessons.html':page('Lessons from other schools',body),'lessons-sources.html':page('Research citations',appendix)}
outputs={name:render_navigation(name,text) for name,text in outputs.items()}
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args()
 for name,text in outputs.items():
  if args.check:
   if (ROOT/name).read_text()!=text:raise SystemExit(name+' is stale; run build_lessons.py')
  else:(ROOT/name).write_text(text)
 print('Research pages '+('verified' if args.check else 'built'))
